
# Load the R packages
rm(list = ls()) 
library(dplyr)
library(readr)
library(janitor)
library(magrittr)

set.seed(12345)

uniform_dist <- runif(n = 1000, 
                      min = 0,  
                      max = 1)
hist(uniform_dist, main="Uniform Distribution Example", xlab="Value")
summary(uniform_dist)

normal_dist <- rnorm(n = 1000,
                     mean = 50,
                     sd = 4)
hist(normal_dist, main="Normal Distribution Example", xlab="Value")
summary(normal_dist)

poisson_dist <- rpois(n = 1000,  
                      lambda = 4)  

hist(poisson_dist, main="Poisson Distribution Example", xlab="Number of Events")
summary(poisson_dist)

binomial_dist <- rbinom(n = 1000,   
                        size = 20,  
                        prob = 0.2)  

hist(binomial_dist, main="Binomial Distribution Example", xlab="Number of Successes")
summary(binomial_dist)

gender <- sample(x = c("M", "F"),  
              size = 1000,      
              replace = TRUE)   

table(gender)
prop.table(table(gender))

marriage_status <- sample(x = c("Single", "Married", "Divorced", "Widowed"),  
                          size = 1000,    
                          replace = TRUE,
                          prob = c(0.35, 0.50, 0.10, 0.05))

table(marriage_status)
prop.table(table(marriage_status))

library(data.table)

synthetic_data1 <- data.table(uniform_dist,
                              normal_dist,
                              poisson_dist,
                              binomial_dist,
                              gender,
                              marriage_status)

print(head(synthetic_data1))
summary(synthetic_data1)
str(synthetic_data1)

# Change gender and marriage_status to factor variables
synthetic_data1$gender <- as.factor(synthetic_data1$gender)
synthetic_data1$marriage_status <- as.factor(synthetic_data1$marriage_status)

# Check the structure of the dataset again
str(synthetic_data1)

install.packages("synthpop")
install.packages("sparklyr")

rm(list = ls())
library(synthpop)

# This will give you the dimensions (rows, columns) of the SD2011 dataset
dim(SD2011)  # Output: 5000 rows, 35 variables

# Show summary information for a subset of variables; here we show only the first five variables for brevity.
synthpop::codebook.syn(SD2011[, 1:5])$tab

# Select a smaller subset of variables for demonstration
mydata <- SD2011[, c(1, 2, 3, 6, 8, 10, 11)]
# Preview the first few rows of the dataset
head(mydata)
# Get a summary of the dataset
summary(mydata)

# Check for negative income values
table(mydata$income[mydata$income < 0], useNA = "ifany")

set.seed(123)

# Synthesise data, handling -8 as a missing value for income
mysyn <- synthpop::syn(mydata, cont.na = list(income = -8))

summary(mysyn)

head(mysyn$syn) 

# Compare the synthetic data with the original data. In most cases, you would need to press "Press return for next variable(s)"
synthpop::compare(mysyn, mydata, stat = "counts")

# Export synthetic data to CSV format
write.syn(mysyn, filename = "mysyn_SD2011", filetype = "csv")

names(mysyn)

mysyn$method
mysyn$predictor.matrix
mysyn$visit.sequence
mysyn$cont.na
mysyn$seed

# Additional comparisons
synthpop::multi.compare(mysyn, mydata, var = "marital", by = "sex")
synthpop::multi.compare(mysyn, mydata, var = "income", by = "agegr")
synthpop::multi.compare(mysyn, mydata, var = "income", by = "edu", cont.type = "boxplot")

library(sparklyr)

sc <- sparklyr::spark_connect(
  master = "local[2]",
  app_name = "synthpop-spark",
  config = sparklyr::spark_config())

# Access the synthetic data generated by synthpop (see Case 1)
synthetic_sd2011 <- mysyn$syn

# Copy the synthetic data frame from R into the Spark session as a Spark table
synthetic_sd2011_tbl <- copy_to(
  sc,
  synthetic_sd2011,
  "synthetic_sd2011",
  overwrite = TRUE
)

# Now you can use dplyr verbs with Spark for scalable processing
result_tbl <- synthetic_sd2011_tbl %>%
  group_by(sex) %>%
  summarise(
    mean_income = mean(income, na.rm = TRUE),
    count = n()
  )
  
result_tbl %>% collect()

spark_disconnect(sc)
